###

# curl https://api.openai.com/v1/images/generations
#  -H 'Content-Type: application/json'
#  -H 'Authorization: Bearer YOUR_API_KEY'
#  -d '{
#  "prompt": "A cute baby sea otter",
#  "n": 2,
#  "size": "1024x1024"
#}'
POST https://api.openai.com/v1/images/generations
Authorization: Bearer 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
Content-Type: application/json

{
  "prompt": "A cute baby sea otter",
  "n": 2,
  "size": "1024x1024"
}

###

